const JOURNEY_MONTHS = [
   { month: 1, title: "FOUNDATION", milestone: "Foundation Set: Onboarding complete, first course done, profile submitted, connections made", tasks: [{ id: "linkedin_course", text: "Complete LinkedIn Warrior course", time: "5-7 days", critical: true }, { id: "submit_profile", text: "Submit profile & speaker materials for audit", deadline: "End of Week 2", critical: true }, { id: "second_course", text: "Choose and start second course (Transformational Leadership)", critical: false }, { id: "connect_10", text: "Connect with 10 Ambassadors on LinkedIn", critical: false }, { id: "post_3x", text: "Post on LinkedIn 3x this month", critical: false }], metrics: { connections: 10, posts: 3, courses: 1 } },
    { month: 2, title: "OPTIMIZE", milestone: "Optimized Presence: Profile updated, first article submitted, active in community", tasks: [{ id: "implement_audit", text: "Implement audit recommendations", critical: true }, { id: "submit_article_1", text: "Submit your first article (4-6 week review)", critical: true }, { id: "engage_15", text: "Engage with 15 ambassador posts this month", critical: false }, { id: "third_course", text: "Start third course: Science of You", critical: false }], metrics: { engagement: 15, articles: 1, courses: 2 } },
    { month: 3, title: "ENGAGE", milestone: "Engaged Member: Attended event, building relationships, consistent content, impact tracked", tasks: [{ id: "first_event", text: "Attend your first quarterly networking event", critical: true }, { id: "follow_up_3", text: "Follow up with 3 people from event (within 48 hours)", critical: true }, { id: "transformation_post", text: "Post transformation update on LinkedIn (90 days)", critical: false }, { id: "submit_article_2", text: "Submit second article (if first is published)", critical: false }, { id: "update_impact_log", text: "Update your impact log", critical: false }], metrics: { impact: 25, events: 1, posts: 3 } },
    { month: 4, title: "LEAD", milestone: "Leadership Activated: Volunteered for opportunity, all courses complete, growing visibility", tasks: [{ id: "volunteer", text: "Volunteer for a leadership opportunity", critical: true }, { id: "complete_courses", text: "Complete all 4 core courses", critical: true }, { id: "request_recommendation", text: "Request letter of recommendation (if needed)", critical: false }, { id: "post_4x", text: "Post 4x on LinkedIn this month", critical: false }], metrics: { courses: 4, posts: 4, leadership: 1 } },
    { month: 5, title: "AMPLIFY", milestone: "Amplified Impact: Led something, article progress, consistent support", tasks: [{ id: "lead_something", text: "Lead or co-lead something (book club, session, event)", critical: true }, { id: "check_article", text: "Check article status and take action", critical: true }, { id: "daily_engage", text: "Engage with Ambassadors content daily (5 min/day)", critical: false }, { id: "update_impact_5", text: "Update impact log", critical: false }], metrics: { impact: 45, leadership: 2, engagement: 150 } },
    { month: 6, title: "MIDPOINT", milestone: "Halfway Strong: Story shared, podcast scheduled, 50+ people impacted, momentum building", tasks: [{ id: "quarterly_event_2", text: "Attend quarterly networking event", critical: true }, { id: "review_progress", text: "Review your 6-month progress", critical: true }, { id: "schedule_podcast", text: "Schedule your podcast episode", critical: true }, { id: "halfway_story", text: "Post your halfway transformation story", critical: false }], metrics: { impact: 50, events: 2, podcast: 1 } },
    { month: 7, title: "VISIBILITY", milestone: "Visible Leader: Podcast prep underway, leading regularly, strong content cadence", tasks: [{ id: "prep_podcast", text: "Prep for podcast recording", critical: true }, { id: "submit_article_next", text: "Submit next article (if you haven't already)", critical: false }, { id: "lead_second", text: "Host or lead a second opportunity", critical: false }, { id: "post_4x_m7", text: "Post consistently: 4x this month", critical: false }], metrics: { posts: 4, leadership: 3, articles: 2 } },
    { month: 8, title: "EXPAND", milestone: "Expanded Reach: Podcast recorded/scheduled, applied for external opportunities, portfolio growing", tasks: [{ id: "record_podcast", text: "Record podcast episode (if scheduled this month)", critical: true }, { id: "check_partners", text: "Check T4L Partners portal weekly", critical: false }, { id: "update_speaker", text: "Update speaker materials", critical: false }, { id: "speaking_pitch", text: "Submit speaking pitch (outside T4L)", critical: false }, { id: "update_impact_8", text: "Update impact log", critical: false }], metrics: { impact: 70, opportunities: 2 } },
    { month: 9, title: "CONNECT", milestone: "Connected Leader: Deep relationships built, podcast live, third leadership opportunity completed", tasks: [{ id: "quarterly_event_3", text: "Attend quarterly networking event", critical: true }, { id: "follow_up_5", text: "Follow up with 5 people from event", critical: true }, { id: "promote_podcast", text: "Promote podcast episode (when it drops)", critical: false }, { id: "lead_third", text: "Lead or volunteer for third opportunity", critical: false }], metrics: { events: 3, leadership: 4, connections: 50 } },
    { month: 10, title: "ACCELERATE", milestone: "Accelerating: Final articles submitted, 85+ impacted, speaking opportunities in pipeline", tasks: [{ id: "submit_final", text: "Submit final articles", critical: true }, { id: "update_impact_10", text: "Update impact log", critical: true }, { id: "post_impact", text: "Post about your impact journey", critical: false }, { id: "apply_speaking", text: "Apply for 2+ speaking opportunities", critical: false }], metrics: { impact: 85, articles: 4, opportunities: 4 } },
    { month: 11, title: "CELEBRATE", milestone: "Celebrating: Year documented, story shared, impact quantified", tasks: [{ id: "quarterly_event_4", text: "Attend quarterly event", critical: true }, { id: "final_impact", text: "Complete final impact log", critical: true }, { id: "transformation_story", text: "Post full year transformation story", critical: false }, { id: "update_bio", text: "Update bio for event spotlight", critical: false }], metrics: { impact: 100, events: 4 } },
    { month: 12, title: "RENEW", milestone: "Transformation Complete: Full year tracked, portfolio built, thought leadership established, decision made", tasks: [{ id: "review_year", text: "Review your year (articles, sessions, courses, impact)", critical: true }, { id: "update_materials", text: "Update all materials (LinkedIn, speaker sheet, portfolio)", critical: true }, { id: "decide_renewal", text: "Decide on renewal (Top Voices, free tier, or alumni)", critical: false }, { id: "schedule_call", text: "Schedule renewal call with T4L", critical: false }], metrics: { impact: 100, articles: 4, leadership: 4, courses: 4 } }
  ];

  module.exports = JOURNEY_MONTHS ;

